version: '3'
 
services:
  app:
    build:
      context:  ../
      dockerfile: docker/automatica/Dockerfile
    expose:
      - "5001"
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app
      
      
      