version: '3'
 
services:
  automatica_demo:
    build:
      context:  ./
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
 
  nginx:
    image: automaticacore/automaticacore_proxy:develop-latest
    restart: always
    ports:
      - "80:80"
    links:
      - automatica_demo
      
      
      